### ISSUE TITLE
Dang this is good

### ISSUE THREAD

**Issue by Thyssenkrupp234** [MainDabRblx/MainDabUISource#3]
Hey, i am a new developer trying to learn some new languages. I primarily develop on macOS, is C# a good language to learn? A lot of people said it is amazing, and I do have access to a windows partition. I am primarily learning Node.JS right now, and I have already made https://github.com/Link2Linc/Old-Roblox-Cusrsor which is my best app so far. 

I am interested in getting down to the system, so would you recommend NodeJS, python, C#, C, C++, or any other languages?

Sorry for the issue here, but you look really interesting! :)

Thanks for your time,

Thyssenkrupp234 (Lincoln)

**Comment by MainDabRblx** [comment]
Hey @Thyssenkrupp234,

Sorry for the late response. I don't actually know (if anything) about macOS development. However, you would be right about C# being mainly used for .NET framework development. I don't really feel that C# is used for macOS development at all. But if you do decide to do development on Windows, then C# is probably not a bad place to start.

In terms of languages, it really depends what you wish to learn and do. I feel that NodeJS is more leaned towards backend (for web services or something). I also feel that Python is nowadays more for things such as AI and stuff. C# is more for frontend and actual apps in my opinion. I view C and C++ as one of those more "abstract" languages, but I see it used for basically everything. 

I actually don't really know much about these things (despite having played around with them), nor what languages to recommend. However, I hope I tried to explain these languages briefly enough. 

(also the code for MainDab is pretty bad and messy)
