### ISSUE TITLE
yoo werent you MainEx?

### ISSUE THREAD

**Issue by LockWare** [MainDabRblx/MainDabUISource#4]
it was like 2-3 years ago my name was shrodunt, i owned a server named The Kool Kids,

**Comment by MainDabRblx** [comment]
Yeah, it's me. I think I do somewhat remember you, as we kinda lost contact.

**Comment by LockWare** [comment]
yeah we did a long time ago, i even have old dms when i was trolling you with some webhook troll i discovered.

**Comment by MainDabRblx** [comment]
dm me at Main_EX#3888

**Comment by MainDabRblx** [comment]
*Main_EX#3898
