### ISSUE TITLE
dear main_ex

### ISSUE THREAD

**Issue by RenewedFroggo** [MainDabRblx/MainDabUISource#7]
i heard you have a booger wall thats so gross is that true

**Comment by MainDabRblx** [comment]
![IMG-20220812-WA0009.jpg](https://user-images.githubusercontent.com/50540449/184410073-fdd08217-2adf-4728-826d-738578d0fe4d.jpg)

**Comment by Weigurde** [comment]
hello <@766314130880593932>, this is <@809916100363943956> can you please give me my mdsdf roles back after i got kicked

**Comment by MainDabRblx** [comment]
can you not

**Comment by MainDabRblx** [comment]
locking this damn thread
